# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import ledger_pb2 as ledger__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='pieledger',
  syntax='proto3',
  serialized_pb=_b('\n\x0eservices.proto\x12\tpieledger\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cledger.proto\"{\n\x17TransactionQueryRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x02 \x01(\x05\x12\r\n\x05guids\x18\x03 \x03(\t\x12#\n\x07\x61\x63\x63ount\x18\x04 \x01(\x0b\x32\x12.pieledger.Account\"\xcb\x02\n\x11SplitQueryRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x02 \x01(\x05\x12#\n\x07\x61\x63\x63ount\x18\x05 \x01(\x0b\x32\x12.pieledger.Account\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x08 \x01(\t\x12\x10\n\x08transref\x18\t \x01(\t\x12\x31\n\rfrom_datetime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bto_datetime\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x0fstandard_action\x18\x06 \x01(\x0e\x32\x16.pieledger.SplitActionH\x00\x12\x17\n\rcustom_action\x18\x07 \x01(\tH\x00\x42\x0b\n\tby_action\"o\n\x17TransactionAlterRequest\x12+\n\x0btransaction\x18\x01 \x01(\x0b\x32\x16.pieledger.Transaction\x12\'\n\rappend_splits\x18\x02 \x03(\x0b\x32\x10.pieledger.Split2\xa9\x03\n\tPieLedger\x12=\n\x13\x46indOrCreateAccount\x12\x12.pieledger.Account\x1a\x12.pieledger.Account\x12\x36\n\x0c\x41lterAccount\x12\x12.pieledger.Account\x1a\x12.pieledger.Account\x12\x43\n\x11\x43reateTransaction\x12\x16.pieledger.Transaction\x1a\x16.pieledger.Transaction\x12P\n\x10\x46indTransactions\x12\".pieledger.TransactionQueryRequest\x1a\x16.pieledger.Transaction0\x01\x12N\n\x10\x41lterTransaction\x12\".pieledger.TransactionAlterRequest\x1a\x16.pieledger.Transaction\x12>\n\nFindSplits\x12\x1c.pieledger.SplitQueryRequest\x1a\x10.pieledger.Split0\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,ledger__pb2.DESCRIPTOR,])




_TRANSACTIONQUERYREQUEST = _descriptor.Descriptor(
  name='TransactionQueryRequest',
  full_name='pieledger.TransactionQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page_number', full_name='pieledger.TransactionQueryRequest.page_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_per_page', full_name='pieledger.TransactionQueryRequest.result_per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guids', full_name='pieledger.TransactionQueryRequest.guids', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account', full_name='pieledger.TransactionQueryRequest.account', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=199,
)


_SPLITQUERYREQUEST = _descriptor.Descriptor(
  name='SplitQueryRequest',
  full_name='pieledger.SplitQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page_number', full_name='pieledger.SplitQueryRequest.page_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_per_page', full_name='pieledger.SplitQueryRequest.result_per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account', full_name='pieledger.SplitQueryRequest.account', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_name', full_name='pieledger.SplitQueryRequest.account_name', index=3,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transref', full_name='pieledger.SplitQueryRequest.transref', index=4,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_datetime', full_name='pieledger.SplitQueryRequest.from_datetime', index=5,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_datetime', full_name='pieledger.SplitQueryRequest.to_datetime', index=6,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='standard_action', full_name='pieledger.SplitQueryRequest.standard_action', index=7,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_action', full_name='pieledger.SplitQueryRequest.custom_action', index=8,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='by_action', full_name='pieledger.SplitQueryRequest.by_action',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=202,
  serialized_end=533,
)


_TRANSACTIONALTERREQUEST = _descriptor.Descriptor(
  name='TransactionAlterRequest',
  full_name='pieledger.TransactionAlterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='pieledger.TransactionAlterRequest.transaction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='append_splits', full_name='pieledger.TransactionAlterRequest.append_splits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=646,
)

_TRANSACTIONQUERYREQUEST.fields_by_name['account'].message_type = ledger__pb2._ACCOUNT
_SPLITQUERYREQUEST.fields_by_name['account'].message_type = ledger__pb2._ACCOUNT
_SPLITQUERYREQUEST.fields_by_name['from_datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SPLITQUERYREQUEST.fields_by_name['to_datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SPLITQUERYREQUEST.fields_by_name['standard_action'].enum_type = ledger__pb2._SPLITACTION
_SPLITQUERYREQUEST.oneofs_by_name['by_action'].fields.append(
  _SPLITQUERYREQUEST.fields_by_name['standard_action'])
_SPLITQUERYREQUEST.fields_by_name['standard_action'].containing_oneof = _SPLITQUERYREQUEST.oneofs_by_name['by_action']
_SPLITQUERYREQUEST.oneofs_by_name['by_action'].fields.append(
  _SPLITQUERYREQUEST.fields_by_name['custom_action'])
_SPLITQUERYREQUEST.fields_by_name['custom_action'].containing_oneof = _SPLITQUERYREQUEST.oneofs_by_name['by_action']
_TRANSACTIONALTERREQUEST.fields_by_name['transaction'].message_type = ledger__pb2._TRANSACTION
_TRANSACTIONALTERREQUEST.fields_by_name['append_splits'].message_type = ledger__pb2._SPLIT
DESCRIPTOR.message_types_by_name['TransactionQueryRequest'] = _TRANSACTIONQUERYREQUEST
DESCRIPTOR.message_types_by_name['SplitQueryRequest'] = _SPLITQUERYREQUEST
DESCRIPTOR.message_types_by_name['TransactionAlterRequest'] = _TRANSACTIONALTERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionQueryRequest = _reflection.GeneratedProtocolMessageType('TransactionQueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONQUERYREQUEST,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:pieledger.TransactionQueryRequest)
  ))
_sym_db.RegisterMessage(TransactionQueryRequest)

SplitQueryRequest = _reflection.GeneratedProtocolMessageType('SplitQueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPLITQUERYREQUEST,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:pieledger.SplitQueryRequest)
  ))
_sym_db.RegisterMessage(SplitQueryRequest)

TransactionAlterRequest = _reflection.GeneratedProtocolMessageType('TransactionAlterRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONALTERREQUEST,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:pieledger.TransactionAlterRequest)
  ))
_sym_db.RegisterMessage(TransactionAlterRequest)



_PIELEDGER = _descriptor.ServiceDescriptor(
  name='PieLedger',
  full_name='pieledger.PieLedger',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=649,
  serialized_end=1074,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindOrCreateAccount',
    full_name='pieledger.PieLedger.FindOrCreateAccount',
    index=0,
    containing_service=None,
    input_type=ledger__pb2._ACCOUNT,
    output_type=ledger__pb2._ACCOUNT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AlterAccount',
    full_name='pieledger.PieLedger.AlterAccount',
    index=1,
    containing_service=None,
    input_type=ledger__pb2._ACCOUNT,
    output_type=ledger__pb2._ACCOUNT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTransaction',
    full_name='pieledger.PieLedger.CreateTransaction',
    index=2,
    containing_service=None,
    input_type=ledger__pb2._TRANSACTION,
    output_type=ledger__pb2._TRANSACTION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTransactions',
    full_name='pieledger.PieLedger.FindTransactions',
    index=3,
    containing_service=None,
    input_type=_TRANSACTIONQUERYREQUEST,
    output_type=ledger__pb2._TRANSACTION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AlterTransaction',
    full_name='pieledger.PieLedger.AlterTransaction',
    index=4,
    containing_service=None,
    input_type=_TRANSACTIONALTERREQUEST,
    output_type=ledger__pb2._TRANSACTION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSplits',
    full_name='pieledger.PieLedger.FindSplits',
    index=5,
    containing_service=None,
    input_type=_SPLITQUERYREQUEST,
    output_type=ledger__pb2._SPLIT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PIELEDGER)

DESCRIPTOR.services_by_name['PieLedger'] = _PIELEDGER

# @@protoc_insertion_point(module_scope)
