# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import ledger_pb2 as ledger__pb2
from . import services_pb2 as services__pb2


class PieLedgerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FindOrCreateAccount = channel.unary_unary(
        '/pieledger.PieLedger/FindOrCreateAccount',
        request_serializer=ledger__pb2.Account.SerializeToString,
        response_deserializer=ledger__pb2.Account.FromString,
        )
    self.AlterAccount = channel.unary_unary(
        '/pieledger.PieLedger/AlterAccount',
        request_serializer=ledger__pb2.Account.SerializeToString,
        response_deserializer=ledger__pb2.Account.FromString,
        )
    self.CreateTransaction = channel.unary_unary(
        '/pieledger.PieLedger/CreateTransaction',
        request_serializer=ledger__pb2.Transaction.SerializeToString,
        response_deserializer=ledger__pb2.Transaction.FromString,
        )
    self.FindTransactions = channel.unary_stream(
        '/pieledger.PieLedger/FindTransactions',
        request_serializer=services__pb2.TransactionQueryRequest.SerializeToString,
        response_deserializer=ledger__pb2.Transaction.FromString,
        )
    self.AlterTransaction = channel.unary_unary(
        '/pieledger.PieLedger/AlterTransaction',
        request_serializer=services__pb2.TransactionAlterRequest.SerializeToString,
        response_deserializer=ledger__pb2.Transaction.FromString,
        )


class PieLedgerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FindOrCreateAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AlterAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AlterTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PieLedgerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FindOrCreateAccount': grpc.unary_unary_rpc_method_handler(
          servicer.FindOrCreateAccount,
          request_deserializer=ledger__pb2.Account.FromString,
          response_serializer=ledger__pb2.Account.SerializeToString,
      ),
      'AlterAccount': grpc.unary_unary_rpc_method_handler(
          servicer.AlterAccount,
          request_deserializer=ledger__pb2.Account.FromString,
          response_serializer=ledger__pb2.Account.SerializeToString,
      ),
      'CreateTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTransaction,
          request_deserializer=ledger__pb2.Transaction.FromString,
          response_serializer=ledger__pb2.Transaction.SerializeToString,
      ),
      'FindTransactions': grpc.unary_stream_rpc_method_handler(
          servicer.FindTransactions,
          request_deserializer=services__pb2.TransactionQueryRequest.FromString,
          response_serializer=ledger__pb2.Transaction.SerializeToString,
      ),
      'AlterTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.AlterTransaction,
          request_deserializer=services__pb2.TransactionAlterRequest.FromString,
          response_serializer=ledger__pb2.Transaction.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pieledger.PieLedger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
